[2025-01-26T14:38:27.932+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T14:38:27.949+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcp_ingest.task_number_2 manual__2025-01-26T14:33:24.670752+00:00 [queued]>
[2025-01-26T14:38:27.957+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcp_ingest.task_number_2 manual__2025-01-26T14:33:24.670752+00:00 [queued]>
[2025-01-26T14:38:27.957+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-26T14:38:27.970+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_number_2> on 2025-01-26 14:33:24.670752+00:00
[2025-01-26T14:38:27.979+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gcp_ingest', 'task_number_2', 'manual__2025-01-26T14:33:24.670752+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/gcp_ingest_dag.py', '--cfg-path', '/tmp/tmpxspatpwu']
[2025-01-26T14:38:27.981+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask task_number_2
[2025-01-26T14:38:27.983+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=289) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-26T14:38:27.984+0000] {standard_task_runner.py:72} INFO - Started process 290 to run task
[2025-01-26T14:38:28.027+0000] {task_command.py:467} INFO - Running <TaskInstance: gcp_ingest.task_number_2 manual__2025-01-26T14:33:24.670752+00:00 [running]> on host 3ba1a9b99dd9
[2025-01-26T14:38:28.121+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcp_ingest' AIRFLOW_CTX_TASK_ID='task_number_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T14:33:24.670752+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T14:33:24.670752+00:00'
[2025-01-26T14:38:28.122+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T14:38:28.132+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-26T14:38:28.133+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'head -n 10 /tmp/downloaded_data.csv']
[2025-01-26T14:38:28.142+0000] {subprocess.py:99} INFO - Output:
[2025-01-26T14:38:28.146+0000] {subprocess.py:106} INFO - <?xml version="1.0" encoding="UTF-8"?>
[2025-01-26T14:38:28.146+0000] {subprocess.py:106} INFO - <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>M5PGN8V5MW6P11M0</RequestId><HostId>MJV61sBeRYVajKbQn62Ta4PuwxiquvLZCaH4uBU+H7aUGWw6hG/2djPOwJ7yclagl6EbQ0zaTmSqeHLCWhfjReXDX+1oGhVHKugr7qT8jUU=</HostId></Error>
[2025-01-26T14:38:28.146+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-26T14:38:28.171+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T14:38:28.171+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=gcp_ingest, task_id=task_number_2, run_id=manual__2025-01-26T14:33:24.670752+00:00, execution_date=20250126T143324, start_date=20250126T143827, end_date=20250126T143828
[2025-01-26T14:38:28.200+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T14:38:28.213+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T14:38:28.214+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
